{
  "type": "class",
  "name": "TestRuntimeException",
  "qualified_name": "net.minecraft.test.TestRuntimeException",
  "package": "net.minecraft.test",
  "modifiers": [
    "public",
    "class"
  ],
  "annotations": [],
  "description": "",
  "inheritance": {
    "extends": null,
    "implements": [],
    "inheritance_tree": [
      "java.lang.Object",
      "java.lang.Throwable",
      "java.lang.Exception",
      "java.lang.RuntimeException"
    ]
  },
  "nested_classes": [],
  "fields": [],
  "constructors": [
    {
      "name": "TestRuntimeException",
      "modifiers": [
        "public"
      ],
      "parameters": [
        {
          "name": "p_i226064_1_",
          "type": "String",
          "annotations": []
        }
      ],
      "description": "",
      "deprecated": false
    }
  ],
  "methods": [],
  "enum_constants": [],
  "since": null,
  "deprecated": false,
  "source_file": "Frameworks/1.16.5/net/minecraft/test/TestRuntimeException.html"
}