{
  "type": "class",
  "name": "DefaultUncaughtExceptionHandlerWithName",
  "qualified_name": "net.minecraft.util.DefaultUncaughtExceptionHandlerWithName",
  "package": "net.minecraft.util",
  "modifiers": [],
  "annotations": [],
  "description": "",
  "inheritance": {
    "extends": null,
    "implements": [],
    "inheritance_tree": []
  },
  "nested_classes": [],
  "fields": [],
  "constructors": [
    {
      "name": "DefaultUncaughtExceptionHandlerWithName",
      "modifiers": [],
      "parameters": [],
      "description": "",
      "deprecated": false
    }
  ],
  "methods": [
    {
      "name": "uncaughtException",
      "modifiers": [
        "public"
      ],
      "return_type": "",
      "parameters": [],
      "description": "",
      "deprecated": false
    }
  ],
  "enum_constants": [],
  "since": null,
  "deprecated": false,
  "source_file": "Frameworks/1.13.2/net/minecraft/util/DefaultUncaughtExceptionHandlerWithName.html"
}